"""Description of changes8

Revision ID: 21cfa4487d69
Revises: df663b3d9995
Create Date: 2024-03-19 19:12:50.233290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cfa4487d69'
down_revision = 'df663b3d9995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('mode_of_transport', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('distance_traveled', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('endpoint_location', sa.String(length=100), nullable=True))
        batch_op.drop_column('gps_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gps_data', sa.TEXT(), nullable=True))
        batch_op.drop_column('endpoint_location')
        batch_op.drop_column('distance_traveled')
        batch_op.drop_column('mode_of_transport')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
