"""Description of changes1

Revision ID: 26a8e3f9d1b7
Revises: a2b6c272960e
Create Date: 2024-03-23 02:02:29.982025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8e3f9d1b7'
down_revision = 'a2b6c272960e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        # Name the unique constraint for stripe_customer_id
        batch_op.create_unique_constraint('uq_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        # Refer to the unique constraint by the name given during the upgrade
        batch_op.drop_constraint('uq_stripe_customer_id', type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
