"""Added friend request mang

Revision ID: 3fb2b6169175
Revises: c426a1d19178
Create Date: 2024-03-27 16:28:29.127940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb2b6169175'
down_revision = 'c426a1d19178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requestee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requestee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'requester_id', 'requestee_id')
    )
    op.drop_table('journey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('journey_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('start_location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('end_location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('mode_of_transport', sa.VARCHAR(length=50), nullable=False),
    sa.Column('distance_traveled', sa.FLOAT(), nullable=True),
    sa.Column('endpoint_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
