"""added payment method

Revision ID: 57f4c177ec48
Revises: 91ac38060cad
Create Date: 2024-05-04 18:13:31.985687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f4c177ec48'
down_revision = '91ac38060cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('card_expiry_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('card_expiry_date')
        batch_op.drop_column('payment_method_type')

    # ### end Alembic commands ###
