"""Description of changes1

Revision ID: 71c5f0c7c72d
Revises: dbc04d3af050
Create Date: 2024-03-22 22:21:57.744339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c5f0c7c72d'
down_revision = 'dbc04d3af050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_stripe_customer_id', type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
