"""revenue  model removed

Revision ID: 75c5757cd760
Revises: a936a1fe8273
Create Date: 2024-05-08 03:46:06.988902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c5757cd760'
down_revision = 'a936a1fe8273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenue_estimate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_estimate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_revenue', sa.FLOAT(), nullable=False),
    sa.Column('calculation_details', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
