"""journey model updated

Revision ID: 8fcaefdf9756
Revises: 57f4c177ec48
Create Date: 2024-05-05 00:27:42.625384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcaefdf9756'
down_revision = '57f4c177ec48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.drop_column('origin')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('destination')
        batch_op.drop_column('waypoints')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waypoints', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
