"""journey model updated2

Revision ID: a936a1fe8273
Revises: 8fcaefdf9756
Create Date: 2024-05-05 22:37:01.350752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a936a1fe8273'
down_revision = '8fcaefdf9756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
