"""Description of changes6

Revision ID: b6f8c9c3f9c9
Revises: bcad70a4fe67
Create Date: 2024-03-16 01:51:00.757022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f8c9c3f9c9'
down_revision = 'bcad70a4fe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
