"""Added the Journey Record column2

Revision ID: c426a1d19178
Revises: de8103d49352
Create Date: 2024-03-24 23:52:43.604285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c426a1d19178'
down_revision = 'de8103d49352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
