"""Added the Journey Record column1

Revision ID: de8103d49352
Revises: 9758bc730e72
Create Date: 2024-03-24 23:02:31.589838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8103d49352'
down_revision = '9758bc730e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=True))
        batch_op.alter_column('waypoints',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('start_location')
        batch_op.drop_column('end_location')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journey_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_location', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('start_location', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('waypoints',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('time_taken')
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
