"""Description of changes7

Revision ID: df663b3d9995
Revises: b6f8c9c3f9c9
Create Date: 2024-03-19 16:32:51.602149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df663b3d9995'
down_revision = 'b6f8c9c3f9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_start_date')

    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
