"""fixed Next plan bug

Revision ID: ef2f500f5709
Revises: 5dc83430d569
Create Date: 2024-05-04 14:20:23.185337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2f500f5709'
down_revision = '5dc83430d569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.alter_column('next_plan_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_stripe_price_id', ['stripe_price_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stripe_price_id', type_='unique')
        batch_op.alter_column('next_plan_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
