"""Description of changes1

Revision ID: f048ab7f2f16
Revises: b8e4247f0526
Create Date: 2024-03-23 01:27:11.870646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f048ab7f2f16'
down_revision = 'b8e4247f0526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_users_subscription_plan', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_subscription_plan', type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')
        batch_op.drop_column('subscription_start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_subscription_plan', 'subscription_plan', ['subscription_plan_id'], ['id'])

    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_subscription_plan', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
