name: pytest
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # This checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      working-directory: team-project-team-15/software_project

    - name: Run pytest
      run: |
        pytest test/
      working-directory: team-project-team-15/software_project
